### ISSUE TITLE
メインメニューのスクロールバーが折り返されない件について

### ISSUE THREAD

**Issue by sama55** [qrac/musubii#45]
qracさんはじめまして。とてもよいフレームワークですね。一つ教えてください。下記デモをモバイルサイズで表示した場合、メインメニューにスクロールバーが表示される（折り返されない）のは意図した（何らかの外的要因による）挙動でしょうか？また、このことに関連することとして、DOCUMENTATIONには他のフレームワークによくあるナビゲーション部品(nav/navbar)が見当たりませんが、これは、今後開発予定なのか、それとも何らかの設計思想があって敢えて作っていないのでしょうか？
https://qrac.github.io/musubii/
![2017-05-26_081220](https://cloud.githubusercontent.com/assets/556681/26474299/229bde3e-41eb-11e7-86b5-c596fc2363e4.jpg)
不躾な質問ですが、どうぞ宜しくお願いします。

**Comment by qrac** [comment]
samaさん、ご質問ありがとうございます！

ナビゲーションが折り返さないのは意図的なもので、[Bootstrap](https://v4-alpha.getbootstrap.com/components/navs/)・[Semantic UI](https://semantic-ui.com/collections/menu.html)・[Bulma](http://bulma.io/documentation/components/nav/)・[Material Design Lite](https://getmdl.io/components/index.html#layout-section)などを参考に作りました。ナビが横にスクロールする認識が一般的になっているのと、メインコンテンツの位置を下げない狙いがあります。

スクロールバーが表示されるのはWindowsの特長なので、iPhoneやAndroidで表示した場合には違和感がないかと思います。Windowsの場合も[デベロッパーツール](https://www.webprofessional.jp/use-mobile-emulation-mode-chrome/)でスクロールバーが出ない状態を確認できます。

![musubii-issue-17052601](https://cloud.githubusercontent.com/assets/9658016/26477795/232ebee4-4203-11e7-955a-9214d598e029.png)

開発当初はフレームワークに含める予定でしたが、ナビのデザインはクセが強いので、プロジェクトによっては邪魔になってしまうだろうなと考え除外しています。

今後リリースするとしても、MUSUBii自体はシンプルなままで、MUSUBiiを使ったテンプレートやテーマに含めて公開することになると思います。

よろしくお願いします。

**Comment by sama55** [comment]
丁寧なご回答ありがとうございます。合点がいきました。確かにBulmaやMaterial Designのメインメニューは同じ挙動をしますね（とても勉強になりました）。ナビ部品を敢えて作らない設計思想もとても共感を覚えました。手前味噌で恐縮ですが、現在日本向けのフレームワークの選定で悩んでまして、自分の中ではMUSUBiiとBulmaが筆頭に挙がっています。
重ねてご回答ありがとうございました。ご活躍を祈念しております。

**Comment by sama55** [comment]
丁寧なご回答ありがとうございます。合点がいきました。確かにBulmaやMaterial Designのメインメニューは同じ挙動をしますね（とても勉強になりました）。ナビ部品を敢えて作らない設計思想もとても共感を覚えました。手前味噌で恐縮ですが、現在日本向けのフレームワークの選定で悩んでまして、自分の中ではMUSUBiiとBulmaが筆頭に挙がっています。
重ねてご回答ありがとうございました。ご活躍を祈念しております。
